### ISSUE TITLE
Hi, looking for some old code of yours.

### ISSUE THREAD

**Issue by davidawesome02** [Simetraa/ProtonWatcher#1]
This is weard, but you seam to be the only person who might still have this code, [https://github.com/barneygale/quarry/issues/88](url)
as the linked repo, [https://github.com/TMShader/QuarryMinecraftServerTests](url) is deleted and the owner [https://github.com/TMShader](url) has not updated any repos in over a year. I am commenting on this project because it seams you are still using github (as of 3 days ago), and your website's network cert is expired (you force https, and I dont think your email still works on there), If you happen to have this code, that would be nice, It seams the issue you faced then is not fixed over a year and 2 releases later.

Thank you

**Comment by Simetraa** [comment]
Hi, would you please send me a message on discord Artemis#5435.

Thanks
